### ISSUE TITLE
Gaokao download not working?

### ISSUE THREAD

**Issue by neubig** [ExpressAI/DataLab#286]
I'm getting the following error when trying to download the gaokao benchmark (for many of the component datasets):
CC: @yyy-Apple @pfliu-nlp 

```
loading splits from datalab for gaokao2018_np1, listening
Downloading and preparing dataset gaokao2018_np1/listening to /Users/gneubig/.cache/expressai/datalab/gaokao2018_np1/listening/1.0.0/d75a7e0357a77742e966aef7744c420a403b032b5e8eca5e8e020cdf36ecf1f5...
Traceback (most recent call last):
  File "/Users/gneubig/work/DataLab/utils/get_dataset_info.py", line 167, in main
    metadata["splits"] = get_splits(file_name, sub_dataset)
  File "/Users/gneubig/work/DataLab/utils/get_dataset_info.py", line 32, in get_splits
    loaded = load_dataset("../datasets/" + dataset, sub_dataset)
  File "/Users/gneubig/work/DataLab/datalabs/load.py", line 2144, in load_dataset
    builder_instance.download_and_prepare(
  File "/Users/gneubig/work/DataLab/datalabs/builder.py", line 747, in download_and_prepare
    self._download_and_prepare(
  File "/Users/gneubig/work/DataLab/datalabs/builder.py", line 868, in _download_and_prepare
    self._prepare_split(split_generator, **prepare_split_kwargs)
  File "/Users/gneubig/work/DataLab/datalabs/builder.py", line 1330, in _prepare_split
    for key, record in utils.tqdm(
  File "/Users/gneubig/opt/anaconda3/envs/explainaboard_web/lib/python3.10/site-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/Users/gneubig/.cache/expressai/modules/datasets_modules/datalab/gaokao2018_np1/d75a7e0357a77742e966aef7744c420a403b032b5e8eca5e8e020cdf36ecf1f5/gaokao2018_np1.py", line 337, in _generate_examples
    context_oracle = data["context_oracle"]
KeyError: 'context_oracle'
```

**Comment by neubig** [comment]
This worked, thank you. This reinforces the usefulness of this issue :)
https://github.com/ExpressAI/DataLab/issues/276
